spring:
  application:
    name: fakebook-server
  datasource:
    url: jdbc:mariadb://localhost:3306/fakebook
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: admin
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update

service:
  auth:
    jwt-secret: jwtsecretkey
    jwt-expire-minutes: 15
    password-encoding-secret: passwordsecretkey


