spring:
  application:
    name: fakebook-server
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    url: jdbc:mariadb://localhost:3306/fakebook
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: admin
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: false
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 773eb25fa6c74fa7af41fe13441a7db1
            client-secret: SqlJ9Fo7WXwrghJj2ikPygdHrIjabQjJ
            redirect-uri: https://8d4f-211-54-164-234.ngrok.io
            authorization-grant-type: authorization_code
            client-name: kakao
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me HTTP/1.1
            user-name-attributes: id

service:
  auth:
    jwt-secret: jwtsecretkey
    access-expire-minutes: 15
    refresh-expire-days: 30
    password-encoding-secret: passwordsecretkey
